version: 2.1

parameters:
  GHA_Actor:
    type: string
    default: ""
  GHA_Action:
    type: string
    default: ""
  GHA_Event:
    type: string
    default: "no-event"
  GHA_Meta:
    type: string
    default: ""

orbs:
  ruby: circleci/ruby@1.4.0

jobs:
  release:
    parameters:
      event:
        type: string
        default: "aaa"
      tag:
        type: string
        default: "bbb"
    docker:
      - image: cimg/ruby:2.6.2
    environment:
      EVENT: << parameters.event >>
      TAG: << parameters.tag >>
      TS: << pipeline.trigger_source >>
    steps:
      - checkout
#      - ruby/install-deps
      - run:
          name: Set up credentials
          command: |
              echo "-${EVENT}-"
              echo "-${TAG}-"
              echo "-${TS}-"
              mkdir -p $HOME/.gem
              touch $HOME/.gem/credentials
              chmod 0600 $HOME/.gem/credentials
              printf -- "---\n:rubygems_api_key: $RUBYGEMS_API_KEY\n" > $HOME/.gem/credentials
      - run:
          name: Build gem
          command: gem build *.gemspec
      # - run:
      #     name: Push gem
      #     command: gem push *.gem

workflows:
  release:
    # when:
    #   equal: [ "release", << pipeline.parameters.GHA_Event >>]
    jobs:
      - release:
          event: << pipeline.parameters.GHA_Event >>
          tag: << pipeline.git.tag >>
          context: gem-publishing
