version: 2.1

orbs:
  ruby: circleci/ruby@1.4.0
  # gem-publisher: doximity/gem-publisher@0.1.3

jobs:
  release:
    docker:
      - image: cimg/ruby:2.7
    steps:
      - checkout
      # - ruby/install-deps
      - run:
          name: Install Deps
          command: bundle install
      - run:
          name: Publish gem to Rubygems
          command: bundle exec rake release

workflows:
  publishing.master:
    when:
      not:
        equal: [master, << pipeline.git.branch >>]
    jobs:
      - release:
          context: gem-publishing
