version: 2.1

orbs:
  ruby: circleci/ruby@1.4.0
  gem-publisher: doximity/gem-publisher@0.1.3

jobs:
  build:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - ruby/install:
          version: '2.6.2'
      - gem-publisher/publish:
          rubygems_api_key: $RUBYGEMS_API_KEY  
          to_rubygems: true

workflows:
  build:
    jobs:
      - publish