version: 2.1

orbs:
  ruby: circleci/ruby@1.4.0
  gem-publisher: doximity/gem-publisher@0.1.3

jobs:
  
  publish:
    docker:
      - image: 'cimg/base:2021.04'
        environment:
          rubygems_api_key: $RUBYGEMS_API_KEY
          to_rubygems: true

    steps:
      - checkout
      - ruby/install:
          version: '2.6.2'
      - gem-publisher/publish

workflows:

    jobs:
      - publish:
          context:
            gem-publishing
